Hghsd 155 populate project home with project info
labdao/app.labdao.xyz pull request #14
Opened 2022-12-08 16:06 UTC by cwest144

updated for new database strucuture

2022-12-09 05:39 UTC, jlevers requested changes

2022-12-09 05:39 UTC, jlevers commented on package.json
> +    "@google-cloud/bigquery": "^6.0.3",
i'm a little confused why this is being added

2022-12-09 05:39 UTC, jlevers commented on pages/projecthome.js
> +            PROJECT WEBSITE: {website}
this should be an actual hyperlink: `<a href={website}>{website}</a>` (or if you wanna clean up the URL to only be optional subdomain, domain, and TLD, that would look better -- can use the javascript URL object to do so i think)

2022-12-09 05:39 UTC, jlevers commented on pages/projecthome.js
> +  const lastName = userData.last_name;
this can be simplified like so:

```js
const {
  first_name: firstName,
  last_name: lastName
} = userData;
```

2022-12-09 05:39 UTC, jlevers commented on pages/projecthome.js
> +  const skills = projectData.skills;
as can this

2022-12-09 05:39 UTC, jlevers commented on pages/projecthome.js
> +  const skills = projectData.skills;
also just want to confirm that everything works properly when the optional fields are empty (last name, skills, etc)

2022-12-09 20:21 UTC, cwest144 commented on pages/projecthome.js
> +            PROJECT WEBSITE: {website}
it seems we should make sure the user submits a valid website in the form, otherwise we can't convert it to a URL object. we should also make sure emails are valid. Can you provide direction for this?

2022-12-10 18:18 UTC, jlevers requested changes

2022-12-10 18:18 UTC, jlevers commented on pages/projecthome.js
> +                    </a>
this doesn't need to change now, but these will probably be buttons with `onClick` attributes rather than links

2022-12-10 18:18 UTC, jlevers commented on pages/projecthome.js
> +  return (
this can still be
```jsx
const ProjectHome = ({ a, b, c }) => (
  <div>{/****/}</div>
);
````

2022-12-10 18:18 UTC, jlevers commented on pages/projecthome.js
> +  const website = projectData.website.replaceAll(" ", "");
this seems to imply there might sometimes be spaces in the url, which shouldn't happen. if you're accounting for accidental spaces at the beginning or end, those should be stripped with [`trim`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/trim) on form submission, so that they're never saved to the backend

2022-12-12 09:19 UTC, jlevers requested changes

2022-12-12 09:19 UTC, jlevers commented on pages/api/project.js
> +    body["website"] = body.website
`body.website` is the same as `body['website']`, so i think this could be simplified to:

```js
body.website = body.website.trim();
const results = Object.values(body);
```

2022-12-12 09:19 UTC, jlevers commented on pages/projecthome.js
> +    website: website
this can be simplified to:

```js
const {
  // ...
  summary: description,
  skills,
  website,
};
```

2022-12-12 09:19 UTC, jlevers commented on pages/projectinfo.js
> +  });
instead of doing this in a `useEffect`, it should all be done through `FormInput` props:

```jsx
const onWebsiteInvalid = (e) => {
  e.target.setCustomValidity('Please enter a valid URL');
};
const onWebsiteChange = (e) => {
  e.target.setCustomValidity('');
};

return (
  <FormInput
    onInvalid={onWebsiteInvalid}
    onInput={onWebsiteInput}
  />
);
```

and then add `onChange` and `onInvalid` to `FormInput`'s `inputProps`
```

2022-12-12 09:19 UTC, jlevers commented on components/FormInput.jsx
> +  type,
where is this prob being used?

2022-12-14 07:24 UTC, jlevers requested changes
tiny formatting change, you can merge when complete

2022-12-14 07:24 UTC, jlevers commented on pages/api/project.js
> +    const redirectUrl = "/projecthome";
single quotes

2022-12-18 20:59 UTC, jlevers approved these changes

2022-12-18 20:59 UTC, merged