Hghsd 165 make wallet address clipboard button
labdao/app.labdao.xyz pull request #7
Opened 2022-12-05 17:04 UTC by cwest144

2022-12-05 19:02 UTC, jlevers commented on pages/projecthome.js
> +    var copyText = document.getElementById("walletAddress");
in react, you generally want to avoid direct DOM manipulation. instead, store the wallet address in state somewhere (once we're pulling from a database, it'll probably come in as a prop from `getServerSideProps`) and use that when copying to the clipboard.

there are two primary reasons to avoid direct DOM manipulation:
1. whatever piece of application state is being changed by accessing the DOM is probably relevant to the broader component or page or application, so the state should be stored at whichever of those levels is most relevant
2. since react re-renders some/all of the DOM quite often, if you don't use a ref to point to a DOM element, you have no guarantee the element you're retrieving with `document.getElementById` will still be on the page by the time you're done modifying it. refs solve that problem...so if you're going to interact with the DOM directly, do it through refs.

https://reactjs.org/docs/refs-and-the-dom.html

2022-12-05 19:04 UTC, jlevers commented on pages/projecthome.js
> +                    <button onClick={copyToClipboard} className="p-2 bg-white/70 hover:bg-white/20 backdrop-blur-xl rounded-md" onMouseEnter={() => setCopied(false)}>
see https://developer.mozilla.org/en-US/docs/Web/API/setTimeout

2022-12-07 06:01 UTC, jlevers requested changes
this is displaying like this for me:

<img width="406" alt="image" src="https://user-images.githubusercontent.com/4974856/206100582-a34abd69-99e1-4863-82a0-ce66c7433ba2.png">

2022-12-07 17:09 UTC, cwest144 commented
I know the code is repetitive, but I have spent 3.5 hours on this now and I am pretty sure this is the best (only?) way to achieve this effect

2022-12-19 22:04 UTC, merged